/****** Object:  Index [IDX_Secondary]    Script Date: 08/18/2008 16:11:00 ******/
CREATE NONCLUSTERED INDEX [IDX_Secondary] ON [dbo].[CollectionPhotos] 
(
	[Order] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]